### ISSUE TITLE
Add a list of the topics already discussed in previous talks

### ISSUE THREAD

**Issue by alejocas** [CodexUdeA/codexudea.github.io#106]
**Is your feature request related to a problem? Please describe.**
Some speakers wants to know if an specific topic was already discussed in a previous (and sometimes, recent) meet, so a list of discussed topics can be helpful to the community in order to give a better idea of what can be shown to everyone in the community.

**Describe the solution you'd like**
It would be good if we can expose a document with topics already discussed.

**Describe alternatives you've considered**
I thought it would be good to show in a list of the given talks with information on the date they were addressed and who was responsible for it, this can be achieved either with Google Sheets or right here on GitHub with Markdown (for solve it in an easy way), it could even be solved with a section on the website.

**Comment by ManuCastrillonM** [comment]
We have that info in this doc -> https://github.com/CodexUdeA/Encuentros/blob/master/REUNIONES_PASADAS.md but it's outdated 😅

**Comment by ManuCastrillonM** [comment]
Hola Alejo! 
Quisiera saber como vas con esta tarea.

**Comment by alejocas** [comment]
Hi Manu, I'm working on this, I need to know: submit a PR with this issue can put me on the contest?
