### ISSUE TITLE
Crear componente - text-section

### ISSUE THREAD

**Issue by ManuCastrillonM** [CodexUdeA/codexudea.github.io#12]
### Descripción

En la carpeta `components` crear la estructura básica para un componente llamado `text-section`.

### Criterios de aceptación

- El componente debe contener la estructura básica de un archivo `.vue` (`<template>` `<script>` y `<style>`)
- La etiqueta `template` debe tener una clase con el mismo nombre del componente
- En `script` se le debe asignar al componente el nombre

### Recursos:

- [Vue single file components](https://vuejs.org/v2/guide/single-file-components.html)

### Notas

N/A

**Comment by santiago-b9826** [comment]
Hola, yo quiero esta
