### ISSUE TITLE
Crear componente - footer

### ISSUE THREAD

**Issue by ManuCastrillonM** [CodexUdeA/codexudea.github.io#16]
### Descripción

En la carpeta `components` crear la estructura básica para un componente llamado `footer`.

### Criterios de aceptación

- El componente debe contener la estructura básica de un archivo `.vue` (`<template>` `<script>` y `<style>`)
- La etiqueta `template` debe tener una clase con el mismo nombre del componente
- En `script` se le debe asignar al componente el nombre

### Recursos:

- [Vue single file components](https://vuejs.org/v2/guide/single-file-components.html)

### 📆 Fecha limite de entrega:
22/10/2018

**Comment by ManuCastrillonM** [comment]
Este issue será reasignado

**Comment by tobon96** [comment]
Lo acabo de mandar, que pena la demora.
