### ISSUE TITLE
Crear asset - team.json

### ISSUE THREAD

**Issue by ManuCastrillonM** [CodexUdeA/codexudea.github.io#17]
### Descripción

Crear en la carpeta `assets/data` un archivo llamado `team.json` el cual contenga un array con la información de los organizadores de Codex en formato json.

### Criterios de aceptación

- La información de cada organizador debe tener la siguiente estructura:
```
{
  name: 'nombre y apellido',
  bio: 'texto',
  picture: 'enlace a foto de perfil de github',
  github: 'enlace al gitHub',
  twitter: 'enlace al twitter'
}
```

### Recursos:

- La información de los organizadores la puede encontrar en [este enlace](https://docs.google.com/spreadsheets/d/1ypNsnK5yoXDR_4suB4N8vouM9a9sKWGvOiaSN9XUyEc/edit?usp=sharing)

### Notas

- Puede dejar en blanco aquella información con la que no se cuente

**Comment by jdiegoisaza** [comment]
Yo voy a hacer este.
