### ISSUE TITLE
Agregar documentación - guia inicial

### ISSUE THREAD

**Issue by ManuCastrillonM** [CodexUdeA/codexudea.github.io#21]
### Descripcion

Como miembro de Codex quiero aprender el proceso para contribuir a este proyecto y así participar en el.

### Acceptance Criteria

- La guia debe mostrar un paso a paso con capturas de pantalla de como:
  - tomar un issue
  - crear una rama del proyecto
  - hacer commit, push y pull
  - crear el pull request
- La guia debe estar en formato .md

### 📆 Fecha limite de entrega:
22/10/2018

**Comment by am9805** [comment]
Yo me encargo del workflow con git y los pr

**Comment by am9805** [comment]
Hey! YO quiero realizar este Issue

**Comment by andresisazaa** [comment]
Yo lo quiero hacer.

**Comment by andresisazaa** [comment]
Ah y organiza la fecha por favor, dice que para el 22 de octubre y estamos a 25.

**Comment by andrespinov** [comment]
Hola, quiero hacer este issue!
