### ISSUE TITLE
Estructurar componente - Hero

### ISSUE THREAD

**Issue by ManuCastrillonM** [CodexUdeA/codexudea.github.io#27]
### Descripción

Crear la estructura HTML y estilos para el componente `hero`
![image](https://user-images.githubusercontent.com/10585946/47170395-8668a880-d2cb-11e8-89a3-505d7db80651.png)

### Criterios de aceptación

- El diseño del componente debe ser consistente con el diseño de referencia
- Para el botón se debe utilizar el componente `button`

### Recursos:

- _Mockups:_ [Enlace a archivo de diseño](https://www.figma.com/proto/P9azXjnC5rbVPcHrP69GDe74/Codex?node-id=68%3A2096&viewport=614%2C22%2C0.145271&scaling=scale-down-width)
- En [este enlace](https://www.figma.com/file/P9azXjnC5rbVPcHrP69GDe74/Codex?node-id=68%3A2096) puedes revisar los detalles del diseño, para ello debes crear una cuenta en [figma.com](https://www.figma.com)
- Para la imagen de fondo puede utilizar una imagen dummy
- Algunos sitios de los que puede obtener [imagenes dummy/placeholder](https://loremipsum.io/21-of-the-best-placeholder-image-generators/)

### Deadline:
Enviar el PR antes de: 26/10/2018
Solucionar los comentarios del PR (en caso de que hayan): 29/10/2018

**Comment by camilocls** [comment]
Voy a trabajar este issue.

**Comment by ManuCastrillonM** [comment]
Reasignado a @camilocls
