### ISSUE TITLE
Estructurar componente - event-card

### ISSUE THREAD

**Issue by ManuCastrillonM** [CodexUdeA/codexudea.github.io#28]
### Descripción

Crear la estructura HTML y estilos para el componente `event-card`
![image](https://user-images.githubusercontent.com/10585946/47170761-77362a80-d2cc-11e8-9980-99352d44d72f.png)

### Criterios de aceptación

- El diseño del componente debe ser consistente con el diseño de referencia

### Recursos:

- _Mockups:_ [Enlace a archivo de diseño](https://www.figma.com/proto/P9azXjnC5rbVPcHrP69GDe74/Codex?node-id=68%3A2096&viewport=614%2C22%2C0.145271&scaling=scale-down-width)
- En [este enlace](https://www.figma.com/file/P9azXjnC5rbVPcHrP69GDe74/Codex?node-id=68%3A2096) puedes revisar los detalles del diseño, para ello debes crear una cuenta en [figma.com](https://www.figma.com)
- Para la imagen de fondo puede utilizar una imagen dummy
- Algunos sitios de los que puede obtener [imagenes dummy/placeholder](https://loremipsum.io/21-of-the-best-placeholder-image-generators/)

### Deadline:
Enviar el PR antes de: TBD
Solucionar los comentarios del PR (en caso de que hayan): TBD

**Comment by ManuCastrillonM** [comment]
Super! Ya está disponible para que trabajes en el

**Comment by andrespinov** [comment]
Hola! Quiero hacer éste issue
