### ISSUE TITLE
Etructurar componente - team-card

### ISSUE THREAD

**Issue by ManuCastrillonM** [CodexUdeA/codexudea.github.io#30]
### Descripción

Crear la estructura HTML y estilos para el componente `team-card`
![image](https://user-images.githubusercontent.com/10585946/47170973-296df200-d2cd-11e8-8ed0-605f89902528.png)

### Criterios de aceptación

- El diseño del componente debe ser consistente con el diseño de referencia
- Para los iconos utilizar la librería [Font Awesome](https://fontawesome.com/v4.7.0/icons/) la cual ya está instalada y configurada en el proyecto

### Recursos:

- _Mockups:_ [Enlace a archivo de diseño](https://www.figma.com/proto/P9azXjnC5rbVPcHrP69GDe74/Codex?node-id=68%3A2096&viewport=614%2C22%2C0.145271&scaling=scale-down-width)
- En [este enlace](https://www.figma.com/file/P9azXjnC5rbVPcHrP69GDe74/Codex?node-id=68%3A2096) puedes revisar los detalles del diseño, para ello debes crear una cuenta en [figma.com](https://www.figma.com)
- Para la imagen de perfil puede utilizar una imagen dummy
- Algunos sitios de los que puede obtener [imagenes dummy/placeholder](https://loremipsum.io/21-of-the-best-placeholder-image-generators/)

### Deadline:
Enviar el PR antes de: 26/10/2018
Solucionar los comentarios del PR (en caso de que hayan): 29/10/2018

**Comment by yaquelinehoyos** [comment]
Hola, yo quiero esta tarea.

**Comment by MartinEliasQ** [comment]
El Issue ya esta habilitado.

**Comment by ManuCastrillonM** [comment]
Reasignado
