### ISSUE TITLE
Estructurar componente - footer

### ISSUE THREAD

**Issue by ManuCastrillonM** [CodexUdeA/codexudea.github.io#31]
### Descripción

Crear la estructura HTML y estilos para el componente `footer`
![image](https://user-images.githubusercontent.com/10585946/47171069-5e7a4480-d2cd-11e8-82fc-42743bad41f4.png)

### Criterios de aceptación

- El CSS debe ser mobile-first
- Utilizar semantic HTML
- El diseño del componente debe ser consistente con el diseño de referencia
- Para los iconos utilizar la librería [Font Awesome](https://fontawesome.com/v4.7.0/icons/) la cual ya está instalada y configurada en el proyecto

### Recursos:

- _Mockups:_ [Enlace a archivo de diseño](https://www.figma.com/proto/P9azXjnC5rbVPcHrP69GDe74/Codex?node-id=68%3A2096&viewport=614%2C22%2C0.145271&scaling=scale-down-width)
- En [este enlace](https://www.figma.com/file/P9azXjnC5rbVPcHrP69GDe74/Codex?node-id=68%3A2096) puedes revisar los detalles del diseño, para ello debes crear una cuenta en [figma.com](https://www.figma.com)

### Deadline:
Enviar el PR antes de: 27/10/2018
Solucionar los comentarios del PR (en caso de que hayan): 30/10/2018

**Comment by wagd96** [comment]
Yo me robo este Issue

**Comment by PilarArroyave** [comment]
Footer, yo te elijo

**Comment by ManuCastrillonM** [comment]
Yaay!!! él esta feliz de que lo hagas
