### ISSUE TITLE
Crear asset - events.json

### ISSUE THREAD

**Issue by ManuCastrillonM** [CodexUdeA/codexudea.github.io#50]
### Descripción

Crear en la carpeta `assets/data` un archivo llamado `events.json` el cual contenga un array con la información de los eventos de Codex en formato json.

### Criterios de aceptación

- La información de cada heroe debe tener la siguiente estructura:
```
{
  date: 'fecha en formato DD/MM/AAAA',
  venue: 'LIS',
  time: 'horario en formato HH:MM en horario militar (24H)',
  talks: [{
    title: 'nombre de la charla1',
    speaker: 'nombre del speaker1'
  },
  {
    title: 'nombre de la charla2',
    speaker: 'nombre del speaker2'
  }]
}
```

### Recursos:

- La información de los eventos la puede encontrar en [este enlace](https://github.com/CodexUdeA/Encuentros/blob/master/REUNIONES_PASADAS.md)
- La hora para los eventos realizados en 2017 es `16:00 - 18:00`
- La hora para los eventos realizados en 2018 es `14:00 - 16:00`, excepto el realizado en la fecha `18/10/2018` el cual fue en horario `17:30 - 20:00`

### Notas

- Puede dejar en blanco aquella información con la que no se cuente

### 📆 Fecha limite de entrega:
22/10/2018

**Comment by Cristian-BFMV** [comment]
Hola, quisiera hacer este issue.
