### ISSUE TITLE
La animación del botón se sale del espacio esperado

### ISSUE THREAD

**Issue by ManuCastrillonM** [CodexUdeA/codexudea.github.io#73]
## Descripción
Al hacer hover en el botón del componente `text-section` la animación sobrepasa lo límites del botón.

## Pasos para reproducirlo
Pasos para reproducir el bug:
1. Ir a la sección 'Quiero dar una charla'
2. Colocar el mouse sobre el botón
4. Ver error

## Comportamiento esperado
La animación se debe visualizar de la misma forma que en el componente hero

## Screenshots
![image](https://user-images.githubusercontent.com/10585946/48789645-863d3d80-ecbb-11e8-9efc-78e8d830c745.png)

## Dispositivos
 - Todos los navegadores

**Comment by andrespinov** [comment]
Hola, me gustaría trabajar en este issue :)
