### ISSUE TITLE
El botón del hero no abre la url esperada

### ISSUE THREAD

**Issue by ManuCastrillonM** [CodexUdeA/codexudea.github.io#74]
## Descripción
El botón del componente hero no está re dirigiendo al formulario enviado como propiedad.

## Pasos para reproducirlo
Pasos para reproducir el bug:
1. Ir al hero
2. Hacer click en el botón 'dar una charla'
4. Ver error

## Comportamiento esperado
Al dar clic en el botón 'dar una charla' debe abrir el enlace: https://docs.google.com/forms/d/e/1FAIpQLSfyeovAO7oIL4Zj3TdHXKJMKBzTo0d9EVxnpU4PgaEtEb4SxA/viewform

## Screenshots
![image](https://user-images.githubusercontent.com/10585946/48789883-0a8fc080-ecbc-11e8-8154-ba743f13ca74.png)

## Dispositivos
 - Todos los navegadores

## Información adicional
Como referencia, puede ver el comportamiento del botón de la sección

**Comment by Addin** [comment]
Hola buenas noches, yo no soy de la Udea pero sí soy de Medellín y soy estudiante igual que ustedes, me interesa aportar a su proyecto.
¿Hay algún problema si hago un PR?

**Comment by ManuCastrillonM** [comment]
Hola Juan Pablo! Bienvenido 🤗 nos encantaría recibir tu aporte.

**Comment by Addin** [comment]
Hola @ManuCastrillonM  qué vergüenza la demora, estaba algo atareado con la universidad, ya he hecho el PR para solucionar este issue.
