### ISSUE TITLE
Scroll horizontal

### ISSUE THREAD

**Issue by ManuCastrillonM** [CodexUdeA/codexudea.github.io#75]
## Descripción
El componente `text-sextion` está generando un scroll horizontal en la página

## Pasos para reproducirlo
Pasos para reproducir el bug:
1. Abrir la página
2. Hacer scroll hacia la derecha
4. Ver error

## Comportamiento esperado
La página no debe tener scroll horizontal

## Screenshots
NA

## Dispositivos
 - Todos los navegadores

## Información adicional
Este problema es causado por la clase `row` del grid, para solucionarlo, se debe asegurar de que las row estan encapsuladas en un container

**Comment by andrespinov** [comment]
Hola! El scroll horizontal lo estuve viendo desde que se empezó el proyecto (cuando sólo estaba la pantalla de "This will be an amaizing project!"). También he tenido el mismo problema en otros proyectos usando flexboxgrid, [aquí está documentado en su repositorio](https://github.com/kristoferjoseph/flexboxgrid/issues/144). Al parecer el proyecto fue abandonado y nunca se solucionó, pero en el enlace anterior proponen varias soluciones. 
La que yo siempre he usado, que no sé qué tan bueno sea hacerlo, es sobreescribir la margen de la clase  row: `.row { margin: 0 }`

**Comment by andrespinov** [comment]
I solve the bug in the PR #85
