### ISSUE TITLE
Agregar 'aria-label' a las secciones

### ISSUE THREAD

**Issue by ManuCastrillonM** [CodexUdeA/codexudea.github.io#78]
## Descripción
Todos los elementos `section` deben tener el atributo `aria-label` 

## Información adicional
[documentación sobre uso de aria-label](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-label_attribute)

**Comment by am9805** [comment]
And mee here too <3
