### ISSUE TITLE
Contribución en servidor

### ISSUE THREAD

**Issue by VasquezLab** [CodexUdeA/codexudea.github.io#89]
**Is your feature request related to a problem? Please describe.**
A ver el crecimiento exponencial del Codex, cada vez se va tener mas información que manejar. Esta información de vuelve engorrosa si se trabaja como un archivo DATA.

**Describe the solution you'd like**
La solución propuesta es la _arquitectura Cloud_ para el sitio de **Codex**, en el cual se puede trabajar un backend mas estructurado, el cual se pueda manejar mas información y realizar diversos módulos que se irían implementando.

**Describe alternatives you've considered**
Como alternativa, mi contribución inicial es el servicio de cloud, creación y administración de la arquitectura.

**Additional context**
Se darían charlas de como implementan de arquitecturas básicas, para contribuir mas con el proyecto de **Codex**

**Comment by MartinEliasQ** [comment]
Hola!,
Evaluaremos la necesidad del servidor. Nos comunicaremos contigo cuando tengamos una ruta clara sobre migrar el sitio a una arquitectura mas robusta.
